export interface ArticleSource {
  title: string;
  url: string;
}

export interface Article {
  slug: string;
  title: string;
  description: string;
  date: string;
  reviewed: string;
  category: string;
  keywords: string[];
  toolSlug: string;
  toolName: string;
  relatedSlugs: string[];
  sources: ArticleSource[];
}

export const ARTICLES: Article[] = [
  {
    slug: 'lease-red-flags',
    title: '10 Lease Clauses That Should Make You Think Twice (and What to Do About Them)',
    description: 'Learn the most common lease red flags renters miss — from automatic renewal traps to joint liability clauses — and how to protect yourself before signing.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Legal',
    keywords: ['lease red flags', 'bad lease clauses', 'rental agreement red flags', 'lease terms to watch out for'],
    toolSlug: 'lease-scanner',
    toolName: 'Lease Red Flag Scanner',
    relatedSlugs: ['security-deposit-laws', 'joint-and-several-liability'],
    sources: [
      { title: 'HUD: Tenant Rights, Laws and Protections', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
      { title: 'Cornell LII: Landlord-Tenant Law', url: 'https://www.law.cornell.edu/wex/landlord-tenant_law' },
      { title: 'Uniform Law Commission: Uniform Residential Landlord and Tenant Act', url: 'https://www.uniformlaws.org/acts/urlta' },
      { title: 'New York Attorney General: Residential Tenants\' Rights Guide', url: 'https://ag.ny.gov/publications/residential-tenants-rights-guide' },
      { title: 'California Department of Real Estate: Guide to Residential Tenants\' and Landlords\' Rights and Responsibilities', url: 'https://www.dre.ca.gov/publications/ResourceGuidebook/2026_Landlord_Tenant_Guide.pdf' },
    ],
  },
  {
    slug: 'beat-ats-resume-filters',
    title: 'How to Beat ATS Resume Filters in 2026: What Actually Works (and What Doesn\'t)',
    description: 'Applicant tracking systems reject 75% of resumes before a human sees them. Here\'s what actually gets you through the filter in 2026.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['how to beat ATS', 'ATS resume filters', 'applicant tracking system tips', 'resume ATS optimization'],
    toolSlug: 'resume-reviewer',
    toolName: 'Resume Reviewer',
    relatedSlugs: ['resume-keywords', 'resume-bullet-examples'],
    sources: [
      { title: 'Harvard Business School: Hidden Workers: Untapped Talent (2021)', url: 'https://www.hbs.edu/managing-the-future-of-work/research/Pages/hidden-workers-untapped-talent.aspx' },
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
      { title: 'O*NET OnLine', url: 'https://www.onetonline.org/' },
    ],
  },
  {
    slug: 'fda-food-recalls-explained',
    title: 'FDA Food Recalls Explained: How to Know If What\'s in Your Kitchen Is Safe',
    description: 'Understand the three classes of FDA food recalls, where to check for active recalls, and how to make sure nothing in your pantry is affected.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['FDA food recalls', 'how to check food recalls', 'food recall lookup', 'is my food recalled'],
    toolSlug: 'food-safety',
    toolName: 'Food Safety Scanner',
    relatedSlugs: ['what-is-bha-in-food', 'food-allergens-label-reading'],
    sources: [
      { title: 'FDA: Recalls, Market Withdrawals & Safety Alerts', url: 'https://www.fda.gov/safety/recalls-market-withdrawals-safety-alerts' },
      { title: 'openFDA: Food Enforcement API', url: 'https://open.fda.gov/apis/food/enforcement/' },
      { title: 'USDA FSIS: Recalls and Public Health Alerts', url: 'https://www.fsis.usda.gov/recalls' },
      { title: '21 CFR Part 7: Enforcement Policy (recall classification)', url: 'https://www.law.cornell.edu/cfr/text/21/part-7' },
    ],
  },
  {
    slug: 'security-deposit-laws',
    title: 'Security Deposit Laws by State: How Much Can a Landlord Actually Charge?',
    description: 'State-by-state guide to security deposit caps, return timelines, and interest requirements. Know your rights before signing a lease.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Legal',
    keywords: ['security deposit laws by state', 'how much can landlord charge security deposit', 'security deposit rules', 'deposit return timeline'],
    toolSlug: 'lease-scanner',
    toolName: 'Lease Red Flag Scanner',
    relatedSlugs: ['lease-red-flags', 'get-security-deposit-back'],
    sources: [
      { title: 'Massachusetts G.L. c. 186 § 15B', url: 'https://malegislature.gov/Laws/GeneralLaws/PartII/TitleI/Chapter186/Section15B' },
      { title: 'Illinois Security Deposit Return Act, 765 ILCS 710', url: 'https://www.ilga.gov/Legislation/ILCS/Articles?ActID=2202&ChapterID=62' },
      { title: 'New York Attorney General: Recovering Rent Security Deposits and Interest (General Obligations Law § 7-108)', url: 'https://ag.ny.gov/resources/individuals/tenants-homeowners/tenants/recovering-rent-security-deposits-and-interest' },
      { title: 'Florida Statutes § 83.49', url: 'http://www.leg.state.fl.us/statutes/index.cfm?App_mode=Display_Statute&URL=0000-0099/0083/Sections/0083.49.html' },
      { title: 'Texas Property Code § 92.101', url: 'https://statutes.capitol.texas.gov/Docs/PR/htm/PR.92.htm' },
      { title: 'California Attorney General: Know Your Rights as a California Tenant, Security Deposits (Civil Code § 1950.5)', url: 'https://oag.ca.gov/system/files/media/Know-Your-Rights-Security-Deposits-English.pdf' },
    ],
  },
  {
    slug: 'resume-keywords',
    title: 'What Keywords Should I Put on My Resume? A Job-by-Job Guide',
    description: 'Generic keyword lists are useless. Learn how to extract the exact keywords from any job description and place them where ATS systems actually look.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['resume keywords', 'keywords for resume', 'ATS keywords', 'resume keyword optimization'],
    toolSlug: 'resume-reviewer',
    toolName: 'Resume Reviewer',
    relatedSlugs: ['beat-ats-resume-filters', 'resume-bullet-examples'],
    sources: [
      { title: 'Harvard Business School: Hidden Workers: Untapped Talent (2021)', url: 'https://www.hbs.edu/managing-the-future-of-work/research/Pages/hidden-workers-untapped-talent.aspx' },
      { title: 'O*NET OnLine', url: 'https://www.onetonline.org/' },
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
      { title: 'BLS Occupational Outlook Handbook', url: 'https://www.bls.gov/ooh/' },
    ],
  },
  {
    slug: 'what-is-bha-in-food',
    title: 'What Is BHA in Food? A Plain-English Guide to the Preservative on Your Ingredient List',
    description: 'BHA shows up in everything from cereal to chips. Here\'s what it actually is, what the science says, and whether you should worry about it.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['what is BHA in food', 'BHA preservative', 'is BHA safe', 'BHA in food products'],
    toolSlug: 'food-safety',
    toolName: 'Food Safety Scanner',
    relatedSlugs: ['fda-food-recalls-explained', 'food-dyes-safety'],
    sources: [
      { title: '21 CFR 172.110: Butylated Hydroxyanisole (BHA)', url: 'https://www.law.cornell.edu/cfr/text/21/172.110' },
      { title: 'IARC Monographs: List of Classifications', url: 'https://monographs.iarc.who.int/list-of-classifications' },
      { title: 'NTP Report on Carcinogens', url: 'https://ntp.niehs.nih.gov/whatwestudy/assessments/cancer/roc' },
      { title: 'Regulation (EC) No 1333/2008 on Food Additives', url: 'https://eur-lex.europa.eu/eli/reg/2008/1333/oj' },
    ],
  },
  {
    slug: 'food-allergens-label-reading',
    title: 'Top 10 Food Allergens in the U.S. and How to Spot Them on a Label',
    description: 'The Big 9 allergens hide under dozens of ingredient names. Learn what to look for on labels and how "contains" statements actually work.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['top food allergens', 'food allergen label reading', 'big 9 allergens', 'hidden allergens in food'],
    toolSlug: 'food-safety',
    toolName: 'Food Safety Scanner',
    relatedSlugs: ['fda-food-recalls-explained', 'what-is-bha-in-food'],
    sources: [
      { title: 'FDA: Food Allergies', url: 'https://www.fda.gov/food/food-labeling-nutrition/food-allergies' },
      { title: 'Food Allergen Labeling and Consumer Protection Act of 2004 (Public Law 108-282)', url: 'https://www.govinfo.gov/content/pkg/PLAW-108publ282/pdf/PLAW-108publ282.pdf' },
      { title: 'FASTER Act of 2021 (Public Law 117-11)', url: 'https://www.govinfo.gov/content/pkg/PLAW-117publ11/pdf/PLAW-117publ11.pdf' },
      { title: '21 CFR 101.91: Gluten-Free Labeling of Food', url: 'https://www.law.cornell.edu/cfr/text/21/101.91' },
    ],
  },
  {
    slug: 'food-dyes-safety',
    title: 'Are Food Dyes Bad for You? What the Science Says About Red 40, Yellow 5, and Blue 1',
    description: 'Food dyes are in more products than you think. Here\'s what the research actually shows about their safety — and what\'s changing in 2026.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['are food dyes bad for you', 'Red 40 safety', 'food dye health effects', 'artificial food coloring'],
    toolSlug: 'food-safety',
    toolName: 'Food Safety Scanner',
    relatedSlugs: ['what-is-bha-in-food', 'food-allergens-label-reading'],
    sources: [
      { title: 'FDA: Color Additives in Foods', url: 'https://www.fda.gov/food/color-additives-information-consumers/color-additives-foods' },
      { title: 'McCann et al., The Lancet (2007): Food Additives and Hyperactive Behaviour in Children', url: 'https://pubmed.ncbi.nlm.nih.gov/17825405/' },
      { title: 'Governor of California: AB 418 Signing Message (California Food Safety Act, 2023)', url: 'https://www.gov.ca.gov/wp-content/uploads/2023/10/AB-418-Signing.pdf' },
      { title: 'Governor of California: Legislation Signed September 28, 2024 (includes AB 2316)', url: 'https://www.gov.ca.gov/2024/09/28/governor-newsom-signs-legislation-to-crack-down-on-processed-food-industry-increase-access-to-healthy-local-foods/' },
      { title: 'Regulation (EC) No 1333/2008 on Food Additives', url: 'https://eur-lex.europa.eu/eli/reg/2008/1333/oj' },
    ],
  },
  {
    slug: 'resume-bullet-examples',
    title: 'Resume Bullet Point Examples That Actually Get Interviews',
    description: 'Stop writing "responsible for" bullets. Learn the CAR framework and see 15 before-and-after examples across industries.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['resume bullet point examples', 'resume bullet points', 'how to write resume bullets', 'CAR framework resume'],
    toolSlug: 'resume-reviewer',
    toolName: 'Resume Reviewer',
    relatedSlugs: ['beat-ats-resume-filters', 'hard-skills-vs-soft-skills'],
    sources: [
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
      { title: 'Purdue OWL: Résumés and Vitas', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/index.html' },
      { title: 'O*NET OnLine', url: 'https://www.onetonline.org/' },
    ],
  },
  {
    slug: 'hard-skills-vs-soft-skills',
    title: 'Hard Skills vs. Soft Skills: What Belongs on Your Resume in 2026',
    description: 'The rules have changed. AI fluency is a hard skill, and soft skills belong in your bullets, not your skills section. Here\'s the 2026 playbook.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['hard skills vs soft skills', 'resume skills section', 'what skills to put on resume', 'soft skills on resume'],
    toolSlug: 'resume-reviewer',
    toolName: 'Resume Reviewer',
    relatedSlugs: ['resume-keywords', 'resume-bullet-examples'],
    sources: [
      { title: 'O*NET OnLine', url: 'https://www.onetonline.org/' },
      { title: 'BLS Occupational Outlook Handbook', url: 'https://www.bls.gov/ooh/' },
      { title: 'Harvard Business School: Hidden Workers: Untapped Talent (2021)', url: 'https://www.hbs.edu/managing-the-future-of-work/research/Pages/hidden-workers-untapped-talent.aspx' },
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
    ],
  },
  {
    slug: 'get-security-deposit-back',
    title: 'How to Get Your Full Security Deposit Back: A Tenant\'s Playbook',
    description: 'A step-by-step guide from move-in photos to demand letters. Protect your deposit before, during, and after your lease.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Legal',
    keywords: ['how to get security deposit back', 'security deposit return', 'landlord keeping deposit', 'deposit demand letter'],
    toolSlug: 'lease-scanner',
    toolName: 'Lease Red Flag Scanner',
    relatedSlugs: ['security-deposit-laws', 'lease-red-flags'],
    sources: [
      { title: 'California Attorney General: Know Your Rights as a California Tenant, Security Deposits (Civil Code § 1950.5)', url: 'https://oag.ca.gov/system/files/media/Know-Your-Rights-Security-Deposits-English.pdf' },
      { title: 'California Courts Self-Help: Guide to Security Deposits in California', url: 'https://selfhelp.courts.ca.gov/guide-security-deposits-california' },
      { title: 'HUD: Tenant Rights, Laws and Protections', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
      { title: 'Cornell LII: Landlord-Tenant Law', url: 'https://www.law.cornell.edu/wex/landlord-tenant_law' },
      { title: 'Uniform Law Commission: Uniform Residential Landlord and Tenant Act', url: 'https://www.uniformlaws.org/acts/urlta' },
    ],
  },
  {
    slug: 'joint-and-several-liability',
    title: 'What Is a Joint and Several Liability Clause? (And Why It Matters for Roommates)',
    description: 'If your roommate stops paying rent, the landlord can come after you for 100% of it. Here\'s how joint and several liability works and what you can do.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Legal',
    keywords: ['joint and several liability lease', 'roommate liability lease', 'lease liability clause', 'roommate lease protection'],
    toolSlug: 'lease-scanner',
    toolName: 'Lease Red Flag Scanner',
    relatedSlugs: ['lease-red-flags', 'security-deposit-laws'],
    sources: [
      { title: 'Cornell LII: Joint and Several Liability', url: 'https://www.law.cornell.edu/wex/joint_and_several_liability' },
      { title: 'Cornell LII: Landlord-Tenant Law', url: 'https://www.law.cornell.edu/wex/landlord-tenant_law' },
      { title: 'HUD: Tenant Rights, Laws and Protections', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
      { title: 'Uniform Law Commission: Uniform Residential Landlord and Tenant Act', url: 'https://www.uniformlaws.org/acts/urlta' },
    ],
  },
  {
    slug: 'natural-vs-organic-food-labels',
    title: 'What\'s the Difference Between \'Natural\' and \'Organic\'? A Buyer\'s Guide',
    description: '"Natural" sounds healthy but means almost nothing legally. Here\'s what food labels actually tell you — and what\'s just marketing.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['natural vs organic', 'organic food labels', 'what does natural mean on food', 'USDA organic certification'],
    toolSlug: 'food-safety',
    toolName: 'Food Safety Scanner',
    relatedSlugs: ['food-allergens-label-reading', 'what-is-bha-in-food'],
    sources: [
      { title: 'USDA National Organic Program', url: 'https://www.ams.usda.gov/about-ams/programs-offices/national-organic-program' },
      { title: '7 CFR Part 205: National Organic Program', url: 'https://www.law.cornell.edu/cfr/text/7/part-205' },
      { title: 'FDA: Use of the Term "Natural" on Food Labeling', url: 'https://www.fda.gov/food/food-labeling-nutrition/use-term-natural-food-labeling' },
      { title: 'USDA FSIS: Meat and Poultry Labeling Terms', url: 'https://www.fsis.usda.gov/food-safety/safe-food-handling-and-preparation/food-safety-basics/meat-and-poultry-labeling-terms' },
    ],
  },
  {
    slug: 'how-to-read-nutrition-label',
    title: 'How to Read a Nutrition Label in Under 60 Seconds',
    description: 'The 5/20 rule, the added sugar trick, and the three numbers that actually matter. A quick guide to reading nutrition labels like a pro.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['how to read nutrition label', 'nutrition facts explained', 'understanding food labels', 'nutrition label guide'],
    toolSlug: 'food-safety',
    toolName: 'Food Safety Scanner',
    relatedSlugs: ['food-allergens-label-reading', 'natural-vs-organic-food-labels'],
    sources: [
      { title: 'FDA: How to Understand and Use the Nutrition Facts Label', url: 'https://www.fda.gov/food/nutrition-facts-label/how-understand-and-use-nutrition-facts-label' },
      { title: '21 CFR 101.9: Nutrition Labeling of Food', url: 'https://www.law.cornell.edu/cfr/text/21/101.9' },
      { title: 'FDA: Added Sugars on the Nutrition Facts Label', url: 'https://www.fda.gov/food/nutrition-facts-label/added-sugars-nutrition-facts-label' },
    ],
  },
  {
    slug: 'how-long-should-resume-be',
    title: 'How Long Should My Resume Be? The One-Page Myth, Explained',
    description: 'The one-page resume rule is outdated. Here\'s when one page, two pages, or even three pages is the right call — based on your actual career stage.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['how long should a resume be', 'one page resume', 'two page resume', 'resume length'],
    toolSlug: 'resume-reviewer',
    toolName: 'Resume Reviewer',
    relatedSlugs: ['beat-ats-resume-filters', 'how-to-write-resume-summary'],
    sources: [
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
      { title: 'Purdue OWL: Résumés and Vitas', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/index.html' },
      { title: 'Harvard Business School: Hidden Workers: Untapped Talent (2021)', url: 'https://www.hbs.edu/managing-the-future-of-work/research/Pages/hidden-workers-untapped-talent.aspx' },
    ],
  },
  {
    slug: 'how-to-write-resume-summary',
    title: 'How to Write a Resume Summary That Doesn\'t Sound Like Everyone Else\'s',
    description: 'Ditch "results-driven professional" forever. Here\'s a formula for writing a resume summary that actually gets read — with 10 examples by career stage.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['how to write resume summary', 'resume summary examples', 'professional summary resume', 'resume summary vs objective'],
    toolSlug: 'resume-reviewer',
    toolName: 'Resume Reviewer',
    relatedSlugs: ['resume-bullet-examples', 'how-long-should-resume-be'],
    sources: [
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
      { title: 'Purdue OWL: Résumés and Vitas', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/index.html' },
      { title: 'Harvard Business School: Hidden Workers: Untapped Talent (2021)', url: 'https://www.hbs.edu/managing-the-future-of-work/research/Pages/hidden-workers-untapped-talent.aspx' },
    ],
  },
  {
    slug: 'can-landlord-raise-rent-mid-lease',
    title: 'Can Your Landlord Raise Rent Mid-Lease? Know Your Rights',
    description: 'Fixed-term lease? Probably not. Month-to-month? Yes, with notice. Here\'s exactly what your landlord can and can\'t do — and what to do if they try.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Legal',
    keywords: ['can landlord raise rent mid lease', 'rent increase rules', 'rent control laws', 'landlord rent raise notice'],
    toolSlug: 'lease-scanner',
    toolName: 'Lease Red Flag Scanner',
    relatedSlugs: ['lease-red-flags', 'landlord-wont-make-repairs'],
    sources: [
      { title: 'California Department of Real Estate: Guide to Residential Tenants\' and Landlords\' Rights and Responsibilities', url: 'https://www.dre.ca.gov/publications/ResourceGuidebook/2026_Landlord_Tenant_Guide.pdf' },
      { title: 'Oregon Revised Statutes Chapter 90 (Residential Landlord and Tenant)', url: 'https://www.oregonlegislature.gov/bills_laws/ors/ors090.html' },
      { title: 'New York Attorney General: Residential Tenants\' Rights Guide', url: 'https://ag.ny.gov/publications/residential-tenants-rights-guide' },
      { title: 'Cornell LII: Landlord-Tenant Law', url: 'https://www.law.cornell.edu/wex/landlord-tenant_law' },
      { title: 'HUD: Tenant Rights, Laws and Protections', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
    ],
  },
  {
    slug: 'landlord-wont-make-repairs',
    title: 'Your Landlord Won\'t Make Repairs. Now What?',
    description: 'From written notices to repair-and-deduct to breaking the lease — a step-by-step guide for tenants dealing with a landlord who ignores maintenance requests.',
    date: '2026-05-08',
    reviewed: '2026-10-08',
    category: 'Legal',
    keywords: ['landlord won\'t make repairs', 'tenant repair rights', 'implied warranty of habitability', 'landlord maintenance obligations'],
    toolSlug: 'lease-scanner',
    toolName: 'Lease Red Flag Scanner',
    relatedSlugs: ['lease-red-flags', 'can-landlord-raise-rent-mid-lease'],
    sources: [
      { title: 'Cornell LII: Implied Warranty of Habitability', url: 'https://www.law.cornell.edu/wex/implied_warranty_of_habitability' },
      { title: 'Cornell LII: Landlord-Tenant Law', url: 'https://www.law.cornell.edu/wex/landlord-tenant_law' },
      { title: 'HUD: Tenant Rights, Laws and Protections', url: 'https://www.hud.gov/topics/rental_assistance/tenantrights' },
      { title: 'Uniform Law Commission: Uniform Residential Landlord and Tenant Act', url: 'https://www.uniformlaws.org/acts/urlta' },
      { title: 'California Department of Real Estate: Guide to Residential Tenants\' and Landlords\' Rights and Responsibilities', url: 'https://www.dre.ca.gov/publications/ResourceGuidebook/2026_Landlord_Tenant_Guide.pdf' },
    ],
  },
  {
    slug: 'how-to-write-cover-letter',
    title: 'How to Write a Cover Letter That Gets Interviews in 2026',
    description: 'Most cover letters fail before the second sentence. Here\'s what hiring managers actually look for, how to structure a letter that works, and the specificity rule that separates good from great.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['how to write a cover letter', 'cover letter 2026', 'cover letter tips', 'cover letter that gets interviews'],
    toolSlug: 'cover-letter-reviewer',
    toolName: 'Cover Letter Reviewer',
    relatedSlugs: ['ats-friendly-cover-letter-format', 'cover-letter-mistakes'],
    sources: [
      { title: 'Purdue OWL: What Is a Cover Letter?', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_1_quick_tips/index.html' },
      { title: 'Purdue OWL: Quick Content Tips for Cover Letters', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_1_quick_tips/quick_content_tips.html' },
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
    ],
  },
  {
    slug: 'ats-friendly-cover-letter-format',
    title: 'ATS-Friendly Cover Letter Format (With Free Template)',
    description: 'Yes, ATS scans your cover letter too. Here\'s the exact format that passes the software filter and still reads well to the hiring manager — including a free copyable template.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['ATS-friendly cover letter format', 'cover letter template', 'cover letter format', 'ATS cover letter'],
    toolSlug: 'cover-letter-reviewer',
    toolName: 'Cover Letter Reviewer',
    relatedSlugs: ['how-to-write-cover-letter', 'cover-letter-vs-resume'],
    sources: [
      { title: 'Harvard Business School: Hidden Workers: Untapped Talent (2021)', url: 'https://www.hbs.edu/managing-the-future-of-work/research/Pages/hidden-workers-untapped-talent.aspx' },
      { title: 'Purdue OWL: What Is a Cover Letter?', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_1_quick_tips/index.html' },
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
    ],
  },
  {
    slug: 'cover-letter-mistakes',
    title: '5 Cover Letter Mistakes That Get You Rejected',
    description: 'The five most common cover letter errors — weak openings, resume repetition, generic letters, length problems, and soft closes — and exactly how to fix each one.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['cover letter mistakes', 'cover letter errors', 'bad cover letter', 'cover letter rejected'],
    toolSlug: 'cover-letter-reviewer',
    toolName: 'Cover Letter Reviewer',
    relatedSlugs: ['how-to-write-cover-letter', 'how-to-start-a-cover-letter'],
    sources: [
      { title: 'Purdue OWL: What Is a Cover Letter?', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_1_quick_tips/index.html' },
      { title: 'Purdue OWL: Cover Letter Workshop', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_workshop/index.html' },
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
    ],
  },
  {
    slug: 'how-to-start-a-cover-letter',
    title: 'How to Start a Cover Letter — 50 Opening Lines That Work',
    description: 'The first sentence of your cover letter is read more carefully than any other. Here are 50 opening lines — achievement-first, company-specific, story-driven, and more — that you can adapt for any role.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['how to start a cover letter', 'cover letter opening lines', 'cover letter first sentence', 'cover letter opening examples'],
    toolSlug: 'cover-letter-reviewer',
    toolName: 'Cover Letter Reviewer',
    relatedSlugs: ['cover-letter-mistakes', 'how-to-write-cover-letter'],
    sources: [
      { title: 'Purdue OWL: Quick Content Tips for Cover Letters', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_1_quick_tips/quick_content_tips.html' },
      { title: 'Purdue OWL: What Is a Cover Letter?', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_1_quick_tips/index.html' },
      { title: 'Purdue OWL: Cover Letter Workshop', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_workshop/index.html' },
    ],
  },
  {
    slug: 'cover-letter-vs-resume',
    title: 'Cover Letter vs Resume: Which Matters More in 2026?',
    description: 'The resume gets you past the ATS filter. The cover letter gets you the interview. Here\'s what each document actually does, when each one matters more, and why you need both working.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['cover letter vs resume', 'does cover letter matter', 'resume vs cover letter', 'cover letter importance 2026'],
    toolSlug: 'cover-letter-reviewer',
    toolName: 'Cover Letter Reviewer',
    relatedSlugs: ['how-to-write-cover-letter', 'ats-friendly-cover-letter-format'],
    sources: [
      { title: 'Purdue OWL: What Is a Cover Letter?', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_1_quick_tips/index.html' },
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
      { title: 'Harvard Business School: Hidden Workers: Untapped Talent (2021)', url: 'https://www.hbs.edu/managing-the-future-of-work/research/Pages/hidden-workers-untapped-talent.aspx' },
    ],
  },
  {
    slug: 'how-long-should-cover-letter-be',
    title: 'How Long Should a Cover Letter Actually Be?',
    description: 'Three to four short paragraphs. Here\'s why that range works, what fits in that space, why longer letters backfire, and a density test to judge every sentence you write.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Career',
    keywords: ['how long should a cover letter be', 'cover letter length', 'cover letter word count', 'cover letter how many pages'],
    toolSlug: 'cover-letter-reviewer',
    toolName: 'Cover Letter Reviewer',
    relatedSlugs: ['how-to-write-cover-letter', 'cover-letter-mistakes'],
    sources: [
      { title: 'Purdue OWL: What Is a Cover Letter?', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_1_quick_tips/index.html' },
      { title: 'Purdue OWL: Quick Content Tips for Cover Letters', url: 'https://owl.purdue.edu/owl/job_search_writing/job_search_letters/cover_letters_1_quick_tips/quick_content_tips.html' },
      { title: 'Purdue OWL: Introduction to and Expectations for Résumés', url: 'https://owl.purdue.edu/owl/job_search_writing/resumes_and_vitas/introduction.html' },
    ],
  },
  {
    slug: 'whats-in-your-face-wash',
    title: "What's Actually in Your Face Wash? A Plain-English Guide",
    description: "The ingredient list on a face wash reads like a chemistry paper — but the categories are simple once you know them. Surfactants, preservatives, humectants, fragrance: here's what each one does and which ones are worth scrutinizing.",
    date: '2026-05-18',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ["what's in face wash", 'face wash ingredients explained', 'skincare ingredients guide', 'cosmetic ingredients plain English'],
    toolSlug: 'cosmetic-ingredient-scanner',
    toolName: 'Cosmetic Ingredient Scanner',
    relatedSlugs: ['parabens-phthalates-sulfates', 'how-to-read-a-cosmetic-label'],
    sources: [
      { title: 'FDA: Cosmetics Labeling Guide', url: 'https://www.fda.gov/cosmetics/cosmetics-labeling-regulations/cosmetics-labeling-guide' },
      { title: '21 CFR Part 701: Cosmetic Labeling', url: 'https://www.law.cornell.edu/cfr/text/21/part-701' },
      { title: 'FDA: Parabens in Cosmetics', url: 'https://www.fda.gov/cosmetics/cosmetic-ingredients/parabens-cosmetics' },
      { title: 'FDA: Fragrances in Cosmetics', url: 'https://www.fda.gov/cosmetics/cosmetic-ingredients/fragrances-cosmetics' },
      { title: 'FDA: Modernization of Cosmetics Regulation Act of 2022 (MoCRA)', url: 'https://www.fda.gov/cosmetics/cosmetics-laws-regulations/modernization-cosmetics-regulation-act-2022-mocra' },
    ],
  },
  {
    slug: 'ewg-hazard-scores-explained',
    title: 'EWG Hazard Scores Explained: Are They Reliable?',
    description: "EWG Skin Deep scores look authoritative. Here's what the 1–10 scale actually measures, where the methodology gets it right, where it overstates risk, and how to use the scores without being misled by them.",
    date: '2026-05-18',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['EWG hazard scores', 'EWG Skin Deep explained', 'EWG scores reliable', 'cosmetic ingredient safety ratings'],
    toolSlug: 'cosmetic-ingredient-scanner',
    toolName: 'Cosmetic Ingredient Scanner',
    relatedSlugs: ['parabens-phthalates-sulfates', 'whats-in-your-face-wash'],
    sources: [
      { title: 'EWG Skin Deep Cosmetics Database', url: 'https://www.ewg.org/skindeep/' },
      { title: 'FDA: Modernization of Cosmetics Regulation Act of 2022 (MoCRA)', url: 'https://www.fda.gov/cosmetics/cosmetics-laws-regulations/modernization-cosmetics-regulation-act-2022-mocra' },
      { title: 'Cosmetic Ingredient Review', url: 'https://www.cir-safety.org/' },
      { title: 'Regulation (EC) No 1223/2009 on Cosmetic Products', url: 'https://eur-lex.europa.eu/eli/reg/2009/1223/oj' },
      { title: 'FDA: Parabens in Cosmetics', url: 'https://www.fda.gov/cosmetics/cosmetic-ingredients/parabens-cosmetics' },
    ],
  },
  {
    slug: 'parabens-phthalates-sulfates',
    title: 'Parabens, Phthalates, Sulfates — What to Actually Worry About',
    description: "Three of the most-avoided ingredient categories in beauty, evaluated honestly. Here's what the evidence says about each one, what the regulatory positions are, and who actually needs to worry.",
    date: '2026-05-18',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['parabens phthalates sulfates', 'are parabens safe', 'phthalates in cosmetics', 'sulfates skin care'],
    toolSlug: 'cosmetic-ingredient-scanner',
    toolName: 'Cosmetic Ingredient Scanner',
    relatedSlugs: ['ewg-hazard-scores-explained', 'pregnancy-safe-skincare'],
    sources: [
      { title: 'FDA: Parabens in Cosmetics', url: 'https://www.fda.gov/cosmetics/cosmetic-ingredients/parabens-cosmetics' },
      { title: 'FDA: Phthalates in Cosmetics', url: 'https://www.fda.gov/cosmetics/cosmetic-ingredients/phthalates-cosmetics' },
      { title: 'FDA: Fragrances in Cosmetics', url: 'https://www.fda.gov/cosmetics/cosmetic-ingredients/fragrances-cosmetics' },
      { title: 'Cosmetic Ingredient Review', url: 'https://www.cir-safety.org/' },
      { title: 'Regulation (EC) No 1223/2009 on Cosmetic Products', url: 'https://eur-lex.europa.eu/eli/reg/2009/1223/oj' },
    ],
  },
  {
    slug: 'how-to-read-a-cosmetic-label',
    title: 'How to Read a Cosmetic Label in 5 Minutes',
    description: "Required vs. voluntary, ingredient order, INCI names, hypoallergenic, non-comedogenic, dermatologist-tested — a plain-English walkthrough of every element of a cosmetic label and what it actually tells you.",
    date: '2026-05-18',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['how to read cosmetic label', 'cosmetic label explained', 'beauty product label guide', 'ingredient list order'],
    toolSlug: 'cosmetic-ingredient-scanner',
    toolName: 'Cosmetic Ingredient Scanner',
    relatedSlugs: ['whats-in-your-face-wash', 'natural-clean-organic-cosmetics'],
    sources: [
      { title: 'FDA: Cosmetics Labeling Guide', url: 'https://www.fda.gov/cosmetics/cosmetics-labeling-regulations/cosmetics-labeling-guide' },
      { title: '21 CFR Part 701: Cosmetic Labeling', url: 'https://www.law.cornell.edu/cfr/text/21/part-701' },
      { title: 'FDA: Modernization of Cosmetics Regulation Act of 2022 (MoCRA)', url: 'https://www.fda.gov/cosmetics/cosmetics-laws-regulations/modernization-cosmetics-regulation-act-2022-mocra' },
      { title: 'FDA: Is It a Cosmetic, a Drug, or Both?', url: 'https://www.fda.gov/cosmetics/cosmetics-laws-regulations/it-cosmetic-drug-or-both-or-it-soap' },
      { title: 'USDA National Organic Program', url: 'https://www.ams.usda.gov/about-ams/programs-offices/national-organic-program' },
    ],
  },
  {
    slug: 'pregnancy-safe-skincare',
    title: 'Pregnancy-Safe Skincare: What to Avoid and Why',
    description: "Retinoids, salicylic acid, hydroquinone, oxybenzone — the ingredients to actually avoid during pregnancy, the ones to use with caution, and a full list of well-studied safe alternatives.",
    date: '2026-05-18',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['pregnancy safe skincare', 'what to avoid in skincare when pregnant', 'pregnancy skincare ingredients', 'safe beauty products pregnancy'],
    toolSlug: 'cosmetic-ingredient-scanner',
    toolName: 'Cosmetic Ingredient Scanner',
    relatedSlugs: ['parabens-phthalates-sulfates', 'ewg-hazard-scores-explained'],
    sources: [
      { title: 'ACOG: Skin Conditions During Pregnancy', url: 'https://www.acog.org/womens-health/faqs/skin-conditions-during-pregnancy' },
      { title: 'FDA: Sunscreen: How to Help Protect Your Skin from the Sun', url: 'https://www.fda.gov/drugs/understanding-over-counter-medicines/sunscreen-how-help-protect-your-skin-sun' },
      { title: 'FDA: Phthalates in Cosmetics', url: 'https://www.fda.gov/cosmetics/cosmetic-ingredients/phthalates-cosmetics' },
      { title: 'FDA: Fragrances in Cosmetics', url: 'https://www.fda.gov/cosmetics/cosmetic-ingredients/fragrances-cosmetics' },
    ],
  },
  {
    slug: 'natural-clean-organic-cosmetics',
    title: "Natural vs Clean vs Organic in Cosmetics: Marketing or Regulation?",
    description: "'Organic' has a legal definition. 'Natural' and 'clean' do not. Here's what each term actually means, which certifications are verified by third parties, and how to evaluate beauty products without being misled by label claims.",
    date: '2026-05-18',
    reviewed: '2026-10-08',
    category: 'Health',
    keywords: ['natural vs clean vs organic cosmetics', 'clean beauty definition', 'organic cosmetics explained', 'natural skincare marketing'],
    toolSlug: 'cosmetic-ingredient-scanner',
    toolName: 'Cosmetic Ingredient Scanner',
    relatedSlugs: ['how-to-read-a-cosmetic-label', 'whats-in-your-face-wash'],
    sources: [
      { title: 'USDA National Organic Program', url: 'https://www.ams.usda.gov/about-ams/programs-offices/national-organic-program' },
      { title: '7 CFR Part 205: National Organic Program', url: 'https://www.law.cornell.edu/cfr/text/7/part-205' },
      { title: 'FDA: Cosmetics Labeling Guide', url: 'https://www.fda.gov/cosmetics/cosmetics-labeling-regulations/cosmetics-labeling-guide' },
      { title: 'FDA: Cosmetics Labeling Claims', url: 'https://www.fda.gov/cosmetics/cosmetics-labeling/cosmetics-labeling-claims' },
    ],
  },
  {
    slug: 'how-to-read-a-privacy-policy',
    title: 'How to Read a Privacy Policy Without Falling Asleep',
    description: 'Privacy policies are long by design. Here\'s which sections actually matter, the phrases that should stop you cold, and a practical 10-minute reading strategy that works for any policy.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Privacy',
    keywords: ['how to read a privacy policy', 'privacy policy explained', 'privacy policy guide', 'understanding privacy policies'],
    toolSlug: 'privacy-policy-translator',
    toolName: 'Privacy Policy Translator',
    relatedSlugs: ['privacy-policy-red-flags', 'what-does-a-privacy-policy-tell-you'],
    sources: [
      { title: 'FTC: Privacy and Security', url: 'https://www.ftc.gov/business-guidance/privacy-security' },
      { title: 'California Attorney General: California Consumer Privacy Act (CCPA)', url: 'https://oag.ca.gov/privacy/ccpa' },
      { title: 'General Data Protection Regulation (Regulation (EU) 2016/679)', url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj' },
      { title: 'Pew Research: How Americans View Data Privacy (2023)', url: 'https://www.pewresearch.org/internet/2023/10/18/how-americans-view-data-privacy/' },
      { title: 'California Privacy Protection Agency', url: 'https://cppa.ca.gov/' },
    ],
  },
  {
    slug: 'what-does-a-privacy-policy-tell-you',
    title: 'What Does a Privacy Policy Actually Tell You? (Plain English Guide)',
    description: 'A section-by-section breakdown of what privacy policies actually disclose — data collection, use, sharing, your rights — and what they deliberately leave out.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Privacy',
    keywords: ['what does a privacy policy tell you', 'privacy policy plain English', 'privacy policy sections explained', 'privacy policy breakdown'],
    toolSlug: 'privacy-policy-translator',
    toolName: 'Privacy Policy Translator',
    relatedSlugs: ['how-to-read-a-privacy-policy', 'how-companies-use-your-data'],
    sources: [
      { title: 'California Attorney General: California Consumer Privacy Act (CCPA)', url: 'https://oag.ca.gov/privacy/ccpa' },
      { title: 'General Data Protection Regulation (Regulation (EU) 2016/679)', url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj' },
      { title: 'COPPA Rule, 16 CFR Part 312', url: 'https://www.law.cornell.edu/cfr/text/16/part-312' },
      { title: 'FTC: Privacy and Security', url: 'https://www.ftc.gov/business-guidance/privacy-security' },
      { title: 'HHS: HIPAA Privacy Rule', url: 'https://www.hhs.gov/hipaa/for-professionals/privacy/index.html' },
      { title: 'Vermont Data Broker Law, 9 V.S.A. § 2446', url: 'https://legislature.vermont.gov/statutes/section/09/062/02446' },
    ],
  },
  {
    slug: 'privacy-policy-red-flags',
    title: '5 Red Flags to Watch for in Any Privacy Policy',
    description: 'Vague sharing language, "we don\'t sell data" exceptions that swallow the rule, silent policy updates, unlimited retention, and undisclosed automated decisions — what to look for and why it matters.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Privacy',
    keywords: ['privacy policy red flags', 'bad privacy policy', 'privacy policy warning signs', 'privacy policy concerns'],
    toolSlug: 'privacy-policy-translator',
    toolName: 'Privacy Policy Translator',
    relatedSlugs: ['how-to-read-a-privacy-policy', 'how-companies-use-your-data'],
    sources: [
      { title: 'FTC: Privacy and Security', url: 'https://www.ftc.gov/business-guidance/privacy-security' },
      { title: 'California Attorney General: California Consumer Privacy Act (CCPA)', url: 'https://oag.ca.gov/privacy/ccpa' },
      { title: 'General Data Protection Regulation (Regulation (EU) 2016/679)', url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj' },
      { title: 'GDPR Article 22: Automated Individual Decision-Making', url: 'https://gdpr-info.eu/art-22-gdpr/' },
      { title: 'Pew Research: How Americans View Data Privacy (2023)', url: 'https://www.pewresearch.org/internet/2023/10/18/how-americans-view-data-privacy/' },
    ],
  },
  {
    slug: 'gdpr-vs-ccpa-privacy-policy',
    title: 'GDPR vs CCPA: What Your Privacy Policy Must Include',
    description: 'The two most important privacy laws in the world require specific disclosures. Here\'s what GDPR and CCPA demand, how they compare, and what they mean for your rights as a consumer.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Privacy',
    keywords: ['GDPR vs CCPA', 'privacy policy requirements', 'GDPR CCPA comparison', 'what must a privacy policy include'],
    toolSlug: 'privacy-policy-translator',
    toolName: 'Privacy Policy Translator',
    relatedSlugs: ['data-rights-2026', 'privacy-policy-red-flags'],
    sources: [
      { title: 'General Data Protection Regulation (Regulation (EU) 2016/679)', url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj' },
      { title: 'GDPR Article 17: Right to Erasure', url: 'https://gdpr-info.eu/art-17-gdpr/' },
      { title: 'GDPR Article 20: Right to Data Portability', url: 'https://gdpr-info.eu/art-20-gdpr/' },
      { title: 'California Attorney General: California Consumer Privacy Act (CCPA)', url: 'https://oag.ca.gov/privacy/ccpa' },
      { title: 'California Privacy Protection Agency', url: 'https://cppa.ca.gov/' },
    ],
  },
  {
    slug: 'how-companies-use-your-data',
    title: 'How Companies Use Your Data After You Click "I Agree"',
    description: 'Behavioral advertising, lookalike modeling, dynamic pricing, risk scoring — the full picture of what actually happens to your data after you accept a privacy policy.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Privacy',
    keywords: ['how companies use your data', 'what happens to your data', 'data after I agree', 'company data practices'],
    toolSlug: 'privacy-policy-translator',
    toolName: 'Privacy Policy Translator',
    relatedSlugs: ['privacy-policy-red-flags', 'what-does-a-privacy-policy-tell-you'],
    sources: [
      { title: 'FTC: Data Brokers: A Call for Transparency and Accountability (2014)', url: 'https://www.ftc.gov/reports/data-brokers-call-transparency-accountability-report-federal-trade-commission-may-2014' },
      { title: 'FTC: A Look Behind the Screens (2024)', url: 'https://www.ftc.gov/reports/look-behind-screens-examining-data-practices-social-media-video-streaming-services' },
      { title: 'FTC: Privacy and Security', url: 'https://www.ftc.gov/business-guidance/privacy-security' },
      { title: 'Pew Research: How Americans View Data Privacy (2023)', url: 'https://www.pewresearch.org/internet/2023/10/18/how-americans-view-data-privacy/' },
      { title: 'California Attorney General: California Consumer Privacy Act (CCPA)', url: 'https://oag.ca.gov/privacy/ccpa' },
    ],
  },
  {
    slug: 'data-rights-2026',
    title: 'What Rights Do You Actually Have Over Your Data in 2026?',
    description: 'The right to know, delete, correct, port, and opt out — who is covered, how to exercise each right, and the honest gap between rights on paper and rights in practice.',
    date: '2026-05-15',
    reviewed: '2026-10-08',
    category: 'Privacy',
    keywords: ['data rights 2026', 'consumer data rights', 'right to delete data', 'GDPR CCPA rights'],
    toolSlug: 'privacy-policy-translator',
    toolName: 'Privacy Policy Translator',
    relatedSlugs: ['gdpr-vs-ccpa-privacy-policy', 'how-to-read-a-privacy-policy'],
    sources: [
      { title: 'General Data Protection Regulation (Regulation (EU) 2016/679)', url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj' },
      { title: 'GDPR Article 17: Right to Erasure', url: 'https://gdpr-info.eu/art-17-gdpr/' },
      { title: 'GDPR Article 20: Right to Data Portability', url: 'https://gdpr-info.eu/art-20-gdpr/' },
      { title: 'California Attorney General: California Consumer Privacy Act (CCPA)', url: 'https://oag.ca.gov/privacy/ccpa' },
      { title: 'California Privacy Protection Agency', url: 'https://cppa.ca.gov/' },
      { title: 'Pew Research: How Americans View Data Privacy (2023)', url: 'https://www.pewresearch.org/internet/2023/10/18/how-americans-view-data-privacy/' },
    ],
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return ARTICLES.find((a) => a.slug === slug);
}

export function getArticlesByTool(toolSlug: string): Article[] {
  return ARTICLES.filter((a) => a.toolSlug === toolSlug);
}

export function getRelatedArticles(article: Article): Article[] {
  return article.relatedSlugs
    .map((s) => ARTICLES.find((a) => a.slug === s))
    .filter((a): a is Article => a !== undefined);
}
